kind: Service
apiVersion: v1
metadata:
  name:  java-app
  namespace: java-app
spec:
  selector:
    app:  java-app
  type: NodePort
  ports:
  - name:  java-app-port
    nodePort: 30082
    port:  80
    targetPort:  8080